name: vitalink
description: A health records and insurance policy manager app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ---- Core UI / Utilities ----
  cupertino_icons: 1.0.8
  provider: 6.1.2
  permission_handler: 11.3.1

  # ---- Storage / Data ----
  shared_preferences: 2.3.2
  flutter_secure_storage: 9.2.2
  path_provider: 2.1.3

  # ---- Network / HTTP ----
  http: 1.2.2

  # ---- Media / Camera ----
  image_picker: 1.0.7       # ✅ safe for Flutter 3.22.x
  image_cropper: 7.0.5       # ✅ before 8.x bump
  image: 4.2.0               # ✅ works with signature >=5.5.0 and launcher_icons
  camera: 0.10.5+9           # ✅ last before Flutter 3.27 bump
  mobile_scanner: 3.4.1      # ✅ stable on Dart 3.4.x

  # ---- ML & PDF ----
  google_mlkit_document_scanner: 0.3.0   # ✅ compatible pre-0.4.x
  google_mlkit_object_detection: 0.11.0  # ✅ compatible pre-0.12.x
  pdf: 3.11.0
  printing: 5.12.0
  flutter_pdfview: 1.3.2

  # ---- Misc UI / Features ----
  qr_flutter: 4.1.0
  signature: 5.5.0             # ✅ upgraded for image 4.x compatibility
  local_auth: 2.3.0
  in_app_purchase: 3.1.11

  # ---- Deep Links ----
  app_links: 6.3.2             # ✅ pinned for Dart <3.5

  # ---- Icons ----
  flutter_launcher_icons: 0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  flutter_launcher_icons: 0.13.1   # ✅ dev task

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/app_icon.png"
